# Generated by Django 6.0.3 on 2026-03-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'право доступа', 'verbose_name_plural': 'права доступа'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'роль', 'verbose_name_plural': 'роли'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'право роли', 'verbose_name_plural': 'права ролей'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'роль пользователя', 'verbose_name_plural': 'роли пользователей'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('read', 'Чтение'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.user'),
        ),
    ]
