# Generated by Django 6.0.3 on 2026-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='idx_users_email',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_users_active',
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('read', 'Чтение'), ('update', 'Обновление'), ('delete', 'Удаление'), ('manage', 'Управление')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_deleted'], name='idx_users_active'),
        ),
    ]
